### PR TITLE
ADL output comparison with original python module 

### PR DESCRIPTION
**Pull request by pietrop**
**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      

https://github.com/bbc/aes31-adl-composer/issues/3

**Describe what the PR does**    

Initially the node module to generate an ADL for SADiE was refactored from the python module by @chrisbaume .
following from a quick test with SADiE that didn't work, https://github.com/bbc/aes31-adl-composer/issues/2 In this PR we are checking the output of the node module ADL against the one from the pythone module https://github.com/bbc/aes31-adl-composer/issues/3#issuecomment-509690290.

**State whether the PR is ready for review or whether it needs extra work**    

Work in progress, setting up PR to make it easier to review the changes.

**Additional context**    

Once this PR is done, we'll still need to test in SADiE as separate issue/PR.

### CODE REVIEW

**Comment by pietrop** [comment]
diff between python and note as of the latest commit. For earlier initial diffs, see notes in issue https://github.com/bbc/aes31-adl-composer/issues/3#issuecomment-509684275

#### `PROJ_CREATE_DATE`
```diff
+ (PROJ_CREATE_DATE)	2019-07-09T17:58:46+00:00
- (PROJ_CREATE_DATE)	2019-07-09T17:58:44.328Z
```
Not sure if the date format matters?

#### `SOURCE_INDEX`
```diff
<SOURCE_INDEX>
+	(Index)	1	(F)	"URL:file://localhost/C:/Audio Files/filename2.wav"	BBCSPEECHEDITOR1	_	_	"_"	"_"
+	(Index)	2	(F)	"URL:file://localhost/C:/Audio Files/filename3.wav"	BBCSPEECHEDITOR2	_	_	"_"	"_"
+	(Index)	3	(F)	"URL:file://localhost/C:/Audio Files/filename1.wav"	BBCSPEECHEDITOR3	_	_	"_"	"_"
-       (Index)	1	(F)	"URL:file://localhost/C:/Audio Files/filename1.wav"	BBCSPEECHEDITOR1	_	_	"_"	"_"
-       (Index)	2	(F)	"URL:file://localhost/C:/Audio Files/filename2.wav"	BBCSPEECHEDITOR2	_	_	"_"	"_"
-       (Index)	3	(F)	"URL:file://localhost/C:/Audio Files/filename3.wav"	BBCSPEECHEDITOR3	_	_	"_"	"_"
</SOURCE_INDEX>
```

Is basicly the order in which the clips are added to the `SOURCE_INDEX`. 
**I might not matter as long as they are unique refs?**

The thing that seems weird is that in python, it's non deterministic, eg if I re run the script I get different order, with different combinations. 

eg 
```python
        (Index)	1	(F)	"URL:file://localhost/C:/Audio Files/filename1.wav"	BBCSPEECHEDITOR1	_	_	"_"	"_"
	(Index)	2	(F)	"URL:file://localhost/C:/Audio Files/filename3.wav"	BBCSPEECHEDITOR2	_	_	"_"	"_"
	(Index)	3	(F)	"URL:file://localhost/C:/Audio Files/filename2.wav"	BBCSPEECHEDITOR3	_	_	"_"	"_"
```

or 
```python
	(Index)	1	(F)	"URL:file://localhost/C:/Audio Files/filename3.wav"	BBCSPEECHEDITOR1	_	_	"_"	"_"
	(Index)	2	(F)	"URL:file://localhost/C:/Audio Files/filename1.wav"	BBCSPEECHEDITOR2	_	_	"_"	"_"
	(Index)	3	(F)	"URL:file://localhost/C:/Audio Files/filename2.wav"	BBCSPEECHEDITOR3	_	_	"_"	"_"
```
etc..


####  `EVENT_LIST`

```diff
+	(Entry)	1	(Cut)	I	2	1~2	1~2	00:00:09:24/0000	00:00:00:00/0000	00:00:05:00/0000	_	(Rem) NAME "Label1"
+	(Entry)	2	(Cut)	I	3	1~2	1~2	00:00:29:24/0000	00:00:05:00/0000	00:00:15:00/0000	_	(Rem) NAME "Label2"
+	(Entry)	3	(Cut)	I	1	1~2	1~2	00:00:49:24/0000	00:00:15:00/0000	00:00:25:00/0000	_	(Rem) NAME "Label3"
+	(Entry)	4	(Cut)	I	3	1~2	1~2	00:01:19:24/0000	00:00:25:00/0000	00:00:35:00/0000	_	(Rem) NAME "Label4"
- 	(Entry)	1	(Cut)	I	1	1~2	1~2	00:00:10:00/0000	00:00:00:00/0000	00:00:05:00/0000	_	(Rem) NAME "Label1"
-	(Entry)	2	(Cut)	I	2	1~2	1~2	00:00:30:00/0000	00:00:05:00/0000	00:00:15:00/0000	_	(Rem) NAME "Label2"
-	(Entry)	3	(Cut)	I	3	1~2	1~2	00:00:50:00/0000	00:00:15:00/0000	00:00:25:00/0000	_	(Rem) NAME "Label3"
-	(Entry)	4	(Cut)	I	2	1~2	1~2	00:01:20:00/0000	00:00:25:00/0000	00:00:35:00/0000	_	(Rem) NAME "Label4"
```

##### 5th colum
the 5th column (counting from left) with the numbers is consistent that it doesn't match between node and python, as it references the clips in `SOURCE_INDEX` - see that section for more details.

##### timecode refs
The diffs between the 6th column of the timecode, are bit more odd, they might be due to the difference in the python timecode module ([`timecode `](https://pypi.org/project/timecode/) vs the [node one `node-timecodes`](https://www.npmjs.com/package/node-timecodes))?

```diff
+ 00:00:09:24/0000
- 00:00:10:00/0000
```
```diff
+ 00:00:29:24/0000
-00:00:30:00/0000
```
```diff
+00:00:49:24/0000
-00:00:50:00/0000
```
```diff
+00:01:19:24/0000
-00:01:20:00/0000
```
cc @bevand10 

```diff
+ python
- node
```

**Comment by chrisbaume** [comment]
> Not sure if the date format matters?

Yes, it matters as that's what the standard says. Might break stuff if it's different.

> It might not matter as long as they are unique refs?

Yes, I think that's true. Hence the Python script is written in a way that doesn't match the IDs to the filenames.

**Comment by pietrop** [comment]
Awesome thanks @chrisbaume !

re time-codes, seems like the TCF Timecode-character expected is `HH:MM:SS:FF/SAMPLE_COUNT` where `SAMPLE_COUNT` is optional

Ok, so to recap what I got left to figure out to wrap up this PR
- [ ] `PROJ_CREATE_DATE` - generated a date format `2019-07-09T17:58:46+00:00` in node/js
- [ ] `EVENT_LIST` timecode conversion seconds + framerate info to `HH:MM:SS:FF/0000`

**Comment by pietrop** [comment]
**update**
_update on the last two tasks + some notes and considerations_

 - [x] `PROJ_CREATE_DATE` - generated a date format 2019-07-09T17:58:46+00:00 in node/js

From the `aes31` docs/specs it seems like the complete representation is encouraged, so after trying with js to get that formatting, right decided to use  [`momentjs`](https://momentjs.com/) time formatting for `PROJ_CREATE_DATE ` as it's just a one liner 
```js
moment().format();                          // 2019-07-10T14:32:11+01:00
```
 - [x] EVENT_LIST timecode conversion seconds + framerate info to HH:MM:SS:FF/0000

Used [`smpte-timecode`](https://www.npmjs.com/package/smpte-timecode) (thanks to @Laurian 's sudgestions)

However the `Timecode` module from `smpte-timecode` takes as arguments `frames`, `frameRate` and a `dropFrame` boolean.

Which means that if our input is in seconds, you first have to multiple it by the frame rate to use it in the module, as shown below
```js
const timeInFrames = seconds * frameRate;
let timecode = new Timecode(timeInFrames, frameRate, false);
```

As far as I can tell, converting to seconds, is not part of the `smpte-timecode` module?

To convert to seconds I modified [this example on stackoverflow](https://stackoverflow.com/questions/31385418/convert-timecode-to-seconds).

```js
const tcToSec = (timecode) =>{
	const hours   = timecode.hours * 60 * 60;
	const minutes = timecode.minutes * 60;
	const seconds = timecode.seconds;
	const frames  = timecode.frames *(1/timecode.frameRate);
	const totalTime = hours + minutes + seconds + frames;

	return totalTime;
};
```

I've raised an issue in their repo to double check https://github.com/CrystalComputerCorp/smpte-timecode/issues/13

**Comment by pietrop** [comment]
Ready for review,

**Note, the following things are for a later PR, and out of scope for this PR**
- refactor string interpolation with ES6 syntax
- refactoring logic involved in ADL creation, in this PR we are keeping as close as possible to the python script to make it easier to cross check, and identify bugs (this can change, and be refactored) once we have tested with SADiE and it works)
- adding tests

**Review points for this PR**
- [ ] running the node example usage, and the python example usage, do you get discrepancies other then expected once? eg
  - [ ] we expect `ADL_UID`,`VER_CREATOR`, `PROJ_TITLE`,`PROJ_ORIGINATOR` to be strings, but with different value/attributes between the two ADL. 
  - [ ] We also expect `PROJ_CREATE_DATE` to be different **but** in the same format. 
  - [ ] `SOURCE_INDEX` is likely to be in different order, as python sets don't preserve order of the items, but we check for the item count and name. 
   - [ ] In `EVENT_LIST` the fifth column referencing the `SOURCE_INDEX` is likely to be different because of the previous point, but we check that the other columns are all the same


Screen Shot 2019-07-10 at 15 22 18

**Comment by pietrop** [comment]
leaving a note following this comment https://github.com/CrystalComputerCorp/smpte-timecode/issues/13#issuecomment-510153435 that `tcToSec` function could be simplified as `timecode.frameCount/timecode.frameRate`

**Pull request merged**
